docs: update github pages links
youki-dev/youki pull request #2969
Opened 2024-10-30 18:05 UTC by tskxz

As referred to in this issue #2967 I updated the links

2024-10-31 15:26 UTC, TBBle requested changes
I had a look, and a bunch of places now have a double-/ in the page URL. I guess you did a search-replace from `containers.github.io/youki` to `youki-dev.github.io/youki/` and now there's a few URLs like `https://youki-dev.github.io/youki//community/introduction.html` in the docs.

URLs that previously ended with `youki` have become URLs that end with `youki/`, and _that_ change looks correct to me (the site redirects to have the trailing `/` in this case) so it's only the double-`//` that need to be fixed.

2024-10-31 15:26 UTC, TBBle commented on README.md
> +[User Documentation](https://youki-dev.github.io/youki//user/basic_setup.html#quick-install)
```suggestion
[User Documentation](https://youki-dev.github.io/youki/user/basic_setup.html#quick-install)
```

2024-10-31 15:26 UTC, TBBle commented on README.md
> +The User and Developer Documentation for youki is hosted at [https://youki-dev.github.io/youki//](https://youki-dev.github.io/youki//)
```suggestion
The User and Developer Documentation for youki is hosted at [https://youki-dev.github.io/youki/](https://youki-dev.github.io/youki/)
```

2024-10-31 15:26 UTC, TBBle commented on README.md
> +Please refer to [our community page](https://youki-dev.github.io/youki//community/introduction.html).
```suggestion
Please refer to [our community page](https://youki-dev.github.io/youki/community/introduction.html).
```

2024-10-31 15:26 UTC, TBBle commented on docs/src/developer/documentation_mdbook.md
> +Currently this documentation is hosted at [https://youki-dev.github.io/youki//](https://youki-dev.github.io/youki//), using GitHub pages. GitHub CI actions are used to automatically check if any file
```suggestion
Currently this documentation is hosted at [https://youki-dev.github.io/youki/](https://youki-dev.github.io/youki/), using GitHub pages. GitHub CI actions are used to automatically check if any files are changed in /docs on each push / PR merge to main branch, and if there are any changes, the mdbook is build and deployed to gh-pages. We use [https://github.com/peaceiris/actions-mdbook](https://github.com/peaceiris/actions-mdbook) to build and then [https://github.com/peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) GitHub action to deploy the mdbook.
```

2024-10-31 15:26 UTC, TBBle commented on tools/wasm-sample/README.md
> +If you want youki to execute the module you must copy it to the root file system of the container and reference it in the args of the config.json. You must also ensure that the annotations contain `"
```suggestion
If you want youki to execute the module you must copy it to the root file system of the container and reference it in the args of the config.json. You must also ensure that the annotations contain `"run.oci.handler": "wasm"` and that youki has been compiled with one of the supported wasm runtimes. For further information please check the [documentation](https://youki-dev.github.io/youki/user/webassembly.html).
```

2024-10-31 18:41 UTC, tskxz commented
> I had a look, and a bunch of places now have a double-/ in the page URL. I guess you did a search-replace from `containers.github.io/youki` to `youki-dev.github.io/youki/` and now there's a few URLs like `https://youki-dev.github.io/youki//community/introduction.html` in the docs.
> 
> URLs that previously ended with `youki` have become URLs that end with `youki/`, and _that_ change looks correct to me (the site redirects to have the trailing `/` in this case) so it's only the double-`//` that need to be fixed.

Thanks for noticing it, I think now it should be fine and fixed.

2024-10-31 19:22 UTC, TBBle approved these changes

2024-11-03 12:38 UTC, utam0k approved these changes

2024-11-03 12:38 UTC, utam0k commented
Thanks!

2024-11-03 12:38 UTC, merged