Add test process rlimits
youki-dev/youki pull request #2977
Opened 2024-11-04 05:47 UTC by sat0ken

This implements the process_rlimits validation in https://github.com/youki-dev/youki/issues/361

2024-11-06 04:42 UTC, YJDoc2 requested changes
Clippy CI failing, also you are not setting the correct runtimetest arg as cmd in the process spec, so the internal validation won't run at all.

2024-11-06 04:48 UTC, YJDoc2 commented
Also, are there any safe alternatives to get the rlimits, maybe via nix crate? https://docs.rs/nix/latest/nix/sys/resource/fn.getrlimit.html
Please use safe alternatives instead of unsafe code wherever possible :)

2024-11-08 06:04 UTC, sat0ken commented
I fixed the code, remove unsafe code and change to use nix.

https://github.com/youki-dev/youki/pull/2977/commits/bc23f9394fb0154203560c4e05d4056b1f162d60

2024-11-10 22:56 UTC, sat0ken commented
@YJDoc2 HI, I've fixed the code according to the comments. Could you please check the code?

2024-11-11 13:33 UTC, YJDoc2 reviewed
two nitpicks, but not blocking change. I'll merge this PR by tom if you don't respond. (Even a comment not necessarily code change) 
To be clear, the nitpicks are not major, so I'm fine for merging this as is, and will merge by tom unless you comment otherwise.

2024-11-11 13:33 UTC, YJDoc2 commented on tests/contest/runtimetest/src/tests.rs
> +                "error type of {:?} hard rlimit expected {:?} , got {:?}",
```suggestion
                "error: rlimit mismatch {:?} hard rlimit expected {:?} , got {:?}",
```
Same for soft limit

2024-11-11 13:33 UTC, YJDoc2 commented on tests/contest/runtimetest/src/tests.rs
> +fn change_resource_type(resource_type: PosixRlimitType) -> Resource {
```suggestion
fn to_nix_resource(resource_type: PosixRlimitType) -> Resource {
```

my reasoning is `change_resource_type` does not express what exactly we are changing it to, but from fn signature it is understandable, so not a strict change req.

2024-11-12 13:11 UTC, YJDoc2 approved these changes

2024-11-12 13:11 UTC, YJDoc2 commented
Going ahead and merging

2024-11-12 13:11 UTC, merged